export const FACT_PACK = [
  {
    slug: 'fact-coordinators',
    chairName: 'FACT Coordinators',
    imageSource: '/images/fact_pack_pictures/coordinators.webp',
    cochairs: [
      {
        name: 'Angela Cabrera',
        chair: 'FACT Co-Coordinator',
        className: 'Senior',
        major: 'Molecular and Cellular Biology',
        bio: "Angela is currently a Senior at the University of Illinois at Urbana-Champaign majoring in Molecular and Cellular Biology and minoring in Psychology on the pre-medicine track. Passionate about sharing her Filipino Culture, Angela became involved in the Philippine Student Association through becoming a member of Barkada; she performed during FACT 2019 and competed in Battle of the Bamboo 2020. Last year, she was part of the 2021 FACT Pack as a Variety Show Co-Coordinator. Outside of PSA, she is the president of UIUC's MCB Leaders, the Vice President of the Professional Pre-Medical Fraternity, Phi Delta Epsilon IL-Beta Chapter, and conducts research at the RIPE Lab at UIUC. She is especially excited to work with her co, Abby, for another year as a FACT Co-Coordinator to promote unity within the Filipino, Asian-American, and other minority communities and to foster the growth toward a better future.",
        imageSource: '/images/fact_pack_pictures/angela_cabrera.webp',
      },
      {
        name: 'Abby Masucol',
        chair: 'FACT Co-Coordinator',
        className: 'Senior',
        major: 'English (Concentration in Media Cultures) and Creative Writing',
        bio: "Abby is a senior studying English with a concentration in Media Cultures and Creative Writing. She is very excited to plan FACT's 30th anniversary with her roommate and best friend, Angela. Abby has been involved with PSA since freshman year. She danced in Barkada, served as a Filipino Culture Night Co-Coordinator sophomore year, and was a FACT 2021 Variety Show Co-Coordinator alongside Angela as well. She believes that it's truly a full circle moment to serve as FACT Co-Coordinators together senior year. Outside of PSA, Abby plays piccolo in the Marching Illini and is the co-president for Sigma Tau Delta, the English Honors Society on campus.",
        imageSource: '/images/fact_pack_pictures/abby_masucol.webp',
      },
    ],
  },
  {
    slug: 'team-fact-managers',
    chairName: 'Team FACT Managers',
    imageSource: '/images/fact_pack_pictures/team_fact_managers.webp',
    cochairs: [
      {
        name: 'Marielle Aromin',
        chair: 'Team FACT Manager',
        className: 'Senior',
        major: 'Civil Engineering',
        bio: "Mari is currently a senior studying Civil Engineering and specializing in both Structural Engineering and Construction Engineering & Management. She enjoys helping out and planning and is excited to utilize these skills as a member of FACT Pack. Within PSA, she has been involved as a member of Barkada, having competed in Battle of the Bamboo 2020 and performed during FACT 2021. During the school year, she works with UIUC's WYSE program that advocates for fostering both excellence and diversity in the STEM community. Outside of PSA, she has also been a previous member of both Women in Engineering and Truth and Beauty.",
        imageSource: '/images/fact_pack_pictures/marielle_aromin.webp',
      },
      {
        name: 'Matthew Panopio',
        chair: 'Team FACT Manager',
        className: 'Junior',
        major: 'Industrial Engineering',
        bio: 'Matthew Panopio is a Junior at the University of Illinois at Urbana-Champaign majoring in Industrial Engineering and minoring in Business. He’s been involved in PSA as a general member, Barkada dancer, and board member. He is excited to help make this year’s conference run smoothly as one of the co-Team FACT managers! In his free time, Matthew enjoys lifting, cooking, and watching K-Dramas.',
        imageSource: '/images/fact_pack_pictures/matthew_panopio.webp',
      },
    ],
  },
  {
    slug: 'hospitality',
    chairName: 'Hospitality',
    imageSource: '/images/fact_pack_pictures/hospitality.webp',
    cochairs: [
      {
        name: 'Jamie Bernal',
        chair: 'Hospitality',
        className: 'Junior',
        major: 'Molecular & Cellular Biology',
        bio: "Jamie is a junior studying Molecular & Cellular Biology. She plans to pursue a career in healthcare as she is passionate about improving health equity and removing healthcare misinformation among Black and Brown communities. Jamie is a current member of the Ko Research Laboratory through the College of Veterinary Medicine at University of Illinois. In her free time, she loves to draw, watch anime, listen to music, and play guitar/ukulele. Jamie has been an active member of PSA since freshman year and is excited to be a new member of this year's FACT pack! Jamie is hoping we can create an amazing FACT weekend for all of this year's delegates.",
        imageSource: '/images/fact_pack_pictures/jamie_bernal.webp',
      },
      {
        name: 'Ranvic Pasaylo',
        chair: 'Hospitality',
        className: 'Junior',
        major: 'Kinesiology (Pre-Nursing)',
        bio: "Ranvic is currently a Junior majoring in Kinesiology on a Pre-Nursing Track. Some things that he likes to do for fun are going to the gym, reading manga, playing basketball, playing videogames, and nerding out over Star Wars and DC/Marvel stuff. He's excited to be more involved with FACT because of how fun the event has been despite being online these past two years. As the event transitions back to in-person, Ranvic is look forward to meeting and making new friends and connections during FACT weekend!",
        imageSource: '/images/fact_pack_pictures/ranvic_pasaylo.webp',
      },
    ],
  },
  {
    slug: 'marketing',
    chairName: 'Marketing',
    imageSource: '/images/fact_pack_pictures/marketing.webp',
    cochairs: [
      {
        name: 'Emily Bautista',
        chair: 'Marketing',
        className: 'Senior',
        major: 'Psychology',
        bio: "Emily is a Senior majoring is Psychology and minoring in Public Health. Throughout college, she's has been involved in PSA through Barkada as well as, being a former social chair. She was also Marketing co-chairs with her Ate Jazmin in 2021. Now she is super excited being Marketing co-chairs with her sib Sarah for FACT 2022! In her free time, she likes to draw, go to the gym (sometimes) and cook. A saying Emily likes to live by is 'Pain is temporary. $wag is forever' and another one is 'GET EXCITED FOR FACT 2022!'",
        imageSource: '/images/fact_pack_pictures/emily_bautista.webp',
      },
      {
        name: 'Sarah Grinen',
        chair: 'Marketing',
        className: 'Senior',
        major: 'Integrative Biology',
        bio: "Sarah is a Senior majoring in Integrative Biology with a minor in Natural Resources and Environmental Sciences. She has been involved with the Philippine Student Association throughout her time at UIUC and has held the positions of Publicity and Vice President Internal. Outside of PSA, she is apart of UIUC's K-Pop Cover Team, Truth and Beauty, and the professional biology fraternity, Beta Psi Omega. She is very excited to work alongside her  FACT Pack members to promote a successful conference this year.",
        imageSource: '/images/fact_pack_pictures/sarah_grinen.webp',
      },
    ],
  },
  {
    slug: 'campus-managers',
    chairName: 'Campus Managers',
    imageSource: '/images/fact_pack_pictures/campus_managers.webp',
    cochairs: [
      {
        name: 'Adrian Dela Cruz',
        chair: 'Campus Manager',
        className: 'Junior',
        major: 'Finance & Information Systems',
        bio: "Adrian Dela Cruz is one of the Campus Managers for FACT this year! He is extremely excited to finally have FACT back in person and can't wait to see everyone coming back to the University of Illinois. A little bit about him: he is a junior studying Finance and Information Systems, and he has been involved with the Philippine Student Association throughout his whole time at college participating in the AKA program, serving as the philanthropy chair, and now a FACT Campus Manager. He is looking forward to seeing you here!",
        imageSource: '/images/fact_pack_pictures/adrian_dela_cruz.webp',
      },
      {
        name: 'Victoria Isabel Pagsanghan',
        chair: 'Campus Manager',
        className: 'Junior',
        major: 'Psychology with a Clinical/Community Concentration',
        bio: "Victoria has always been passionate about her Filipino culture and have always wanted to share it with others. She was heavily involved in my high school's Filipino club, Isang Hakbang, competing in Battle of the Bamboo for 4 years, so she knew she had to join PSA and Barkada when she got to college. During Victoria's sophomore on Barkada, she was Battalion Head. She has made some of her closest friends thanks to PSA and Barkada. Outside of PSA, Victoria is also a member of the Alpha Phi Omega service fraternity and she enjoys watching K-dramas, spending time with her friends, and listening to K-pop groups such as BTS and TXT. ",
        imageSource:
          '/images/fact_pack_pictures/victoria_isabel_pagsanghan.webp',
      },
    ],
  },
  {
    slug: 'variety-show-coordinators',
    chairName: 'Variety Show Coordinators',
    imageSource: '/images/fact_pack_pictures/vshow_coordinators.webp',
    cochairs: [
      {
        name: 'Danielle Herrera',
        chair: 'Variety Show Co-Coordinator',
        className: 'Senior',
        major: 'Molecular and Cellular Biology',
        bio: 'Danielle is currently a Senior studying Molecular and Cellular Biology with a certificate in Forensic Science. She became a member of the Philippine Student Association during freshman year and through Barkada she was able to perform at FACT 2019 and Battle of the Bamboo. Though her past experience has been limited, Danielle is thrilled to be involved once again and help reinvigorate a newfound excitement for this year’s return to in-person FACT! Danielle currently works as a scribe and medical assistant at Carle Health and is planning to pursue a career in the medical field. Outside of the hospital, she spends her time conducting research on campus at PNC laboratory and volunteering with children at CAOS and Crisis Nursery. She is looking forward to working alongside her co-coordinator, Frank, to help create another amazing Variety Show!',
        imageSource: '/images/fact_pack_pictures/danielle_herrera.webp',
      },
      {
        name: 'Frank Cabrera',
        chair: 'Variety Show Co-Coordinator',
        className: 'Senior',
        major: 'English and History (Pre-Law)',
        bio: 'Frank is a senior at UIUC studying English and History on a pre-law track. Frank joined PSA his freshman year creating connections through PSA volleyball nights. His junior year Frank came on board as Athletic Chair for the 2021-2022 school year, facilitating his own volleyball nights, online tournaments and was a facilitator assistant for FACT 2021. Outside of PSA, Frank is involved with RSOs such as the Illinois Coalition Assisting Undocumented Students Education (I-CAUSE), La Colectiva, and the Ecuadorian Student Association (ESA). Frank, alongside his Co-Coordinator, Danielle Herrera, are looking to put on a great variety show!',
        imageSource: '/images/fact_pack_pictures/frank_cabrera.webp',
      },
    ],
  },
  {
    slug: 'media',
    chairName: 'Media',
    imageSource: '/images/fact_pack_pictures/media.webp',
    cochairs: [
      {
        name: 'Gio Marco Talavera',
        chair: 'Media',
        className: 'Senior',
        major: 'Technical Systems Management',
        bio: "Gio is a Senior majoring in Technical Systems Management with minors in Business and Agricultural Health & Safety. His interests include jamming to music, taking photos, and playing basketball. He is currently working for the UIUC CITL's media resource team, where he developed an interest in filming. He was previously involved in FACT 2019 as a photographer but now holds the position of Media co-chair. As Co-chairs with Mark, they aim to deliver spectacular visuals to fully portray our Filipino culture.",
        imageSource: '/images/fact_pack_pictures/gio_talavera.webp',
      },
      {
        name: 'Mark Casco',
        chair: 'Media',
        className: 'Senior',
        major: 'Interdisciplinary Health Sciences',
        bio: 'Senior in Interdisciplinary Health Science with a concentration in Health and Aging. I have a passion for physical activity, work-leisure balance, and educating others. I aspire to specialize within PT, OT, or Nursing, and also explore financial business concurrently.',
        imageSource: '/images/fact_pack_pictures/mark_casco.webp',
      },
    ],
  },
  {
    slug: 'information-technology',
    chairName: 'Information Technology',
    imageSource: '/images/fact_pack_pictures/information_technology.webp',
    cochairs: [
      {
        name: 'Alyssa Daniels',
        chair: 'IT',
        className: 'Junior',
        major: 'Math and Computer Science',
        bio: "Alyssa is a Junior studying Math and Computer Science. She has been very involved in PSA throughout her time at UIUC. She joined Barkada as a Freshman, was PSA's 2021-2022 Webmaster, and is now the organization's Secretary. Outside of PSA, she enjoys dancing, video game development, and tutoring kids in CS. She is excited to be one of the IT Chairs for FACT this year!",
        imageSource: '/images/fact_pack_pictures/alyssa_daniels.webp',
      },
      {
        name: 'Renzo Ledesma',
        chair: 'IT',
        className: 'Senior',
        major: 'Computer Science + Music',
        bio: "Renzo is currently a senior studying Computer Science + Music, interested in using technology and music to make a positive impact on people's lives. Throughout college, they've been involved with PSA by dancing and creating music for Barkada, managing the PSA & FACT websites, and bringing the community together as Team FACT Manager and FCN Co-Coordinator. Outside of PSA, he pursues music production & education and helps develop software for the university. They're excited to make FACT as smooth and exciting as possible as part of IT!",
        imageSource: '/images/fact_pack_pictures/renzo_ledesma.webp',
      },
    ],
  },
];
